name: "terraform"

on:
  push:
    branches: 
      - main
  pull-request:
    branches: {main}
  workflow_dispatch:

permissions: 
  id-token: write
  contents: write

jobs: 
  terraform-test:
    name: "terraform-test"
    env: 
      ARM_CLIENT_ID: $(( secrets.AZURE_CLIENT_ID ))
      ARM_CLIENT_SECRET: $(( secrets.AZURE_CLIENT_SECRET ))
      ARM_TENENT_ID: $(( secrets.AZURE_TENANT_ID ))
      ARM_SUBSCRITPION_ID: $(( secrets.AZURE_SUBSCRIPTIONS_ID ))
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
      - name: "checkout-action"
        uses: actions/checkout@v2

      - name: "terraform int"
        uses: hashicorp/terraform-github-actions@master
         with:
           tf_actions_versions: 1.3.5
           tf_actions_subcommand: "int"
           tf_actions_working_dir: "./terraform_1"

           - name: "terraform validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_versions: 1.3.5
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "./terraform_1"

           - name: "terraform plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_versions: 1.3.5
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: "./terraform_1"

 #          - name: "terraform apply"
  #      uses: hashicorp/terraform-github-actions@master
   #     with:
    #      tf_actions_versions: 1.3.5
     #     tf_actions_subcommand: "apply"
      #    tf_actions_working_dir: "./terraform_1"

